name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: demo_test
      id: demo_test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 3
        max-score: 5
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DEMO_TEST_RESULTS: "${{steps.demo_test.outputs.result}}"
      with:
        runners: demo_test
